import { Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";
import PreloadProvider from "@/context/preload-context";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${playfair.variable}`}>
        <PreloadProvider>{children}</PreloadProvider>
      </body>
    </html>
  );
}
